version: "2"

linters:
  default: standard
  enable:
    - gosec
  exclusions:
    rules:
      # Skip gosec in all test files
      - path: _test\.go
        linters:
          - gosec

run:
  timeout: 6m
