apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  selector:
    matchLabels:
      app: ibm-odf-console
      odf-fs: odf-fs-workspace
      odf: storage.ibm.com
  template:
    metadata:
      labels:
        app: ibm-odf-console
        odf-fs: odf-fs-workspace
        odf: storage.ibm.com
    spec:
      containers:
        - name: ibm-odf-console
          image: ibm-console:latest
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 9003
              protocol: TCP
          volumeMounts:
            - name: ibm-odf-console-serving-cert
              mountPath: /var/serving-cert
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
      volumes:
        - name: ibm-odf-console-serving-cert
          secret:
            secretName: ibm-odf-console-serving-cert
      securityContext:
        runAsNonRoot: true
