namePrefix: ibm-odf-

# Labels to add to all resources and selectors.
commonLabels:
  app: ibm-odf-console
  odf-fs: odf-fs-workspace
  odf: storage.ibm.com

resources:
  - console_init.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ibm-console
    newName: quay.io/ben_menachem
    newTag: 1.5.0
