namePrefix: ibm-odf-

# Labels to add to all resources and selectors.
commonLabels:
  app: ibm-odf-console

resources:
  - console_init.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ibm-console
    newName: docker.io/ibmcom/ibm-storage-odf-plugin
    newTag: 1.1.0
