apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    odf-fs: odf-fs-workspace
  name: ibm-storage-odf-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    odf-fs: odf-fs-workspace
status:
  loadBalancer: {}
