
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    odf-fs: odf-fs-workspace
  name: ibm-storage-odf-operator-metrics-monitor
  namespace: openshift-storage
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      odf-fs: odf-fs-workspace
