
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    odf: storage.ibm.com
  name: ibm-storage-odf-operator-metrics-monitor
  namespace: ibm-storage-odf
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      odf: storage.ibm.com
