apiVersion: v1
kind: Service
metadata:
  labels:
    odf: storage.ibm.com
  name: ibm-storage-odf-operator-metrics-service
  namespace: openshift-storage
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    odf: storage.ibm.com
