# permissions for end users to view flashsystemclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flashsystemcluster-viewer-role
rules:
- apiGroups:
  - odf.ibm.com
  resources:
  - flashsystemclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - odf.ibm.com
  resources:
  - flashsystemclusters/status
  verbs:
  - get
