---
# OLM: BEGIN ROLE
# Aspects for creation of monitoring resources
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flashcluster-monitor
  namespace: ibm-storage-odf
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
# OLM: END ROLE
---
# OLM: BEGIN ROLE BINDING
# Allow creation of monitoring resources
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flashcluster-monitor
  namespace: ibm-storage-odf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flashcluster-monitor
subjects:
- kind: ServiceAccount
  name: ibm-storage-odf-operator
  namespace: ibm-storage-odf
# OLM: END ROLE BINDING
---
# OLM: BEGIN ROLE
# Aspects for metrics collection
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flashcluster-metrics
  namespace: ibm-storage-odf
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
# OLM: END ROLE
---
# OLM: BEGIN ROLE BINDING
# Allow collection of metrics
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flashcluster-metrics
  namespace: ibm-storage-odf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flashcluster-metrics
subjects:
- kind: ServiceAccount
  # change to the serviceaccount and namespace to use for monitoring
  name: prometheus-k8s
  namespace: openshift-monitoring
# OLM: END ROLE BINDING
---

