FROM golang:1.18

RUN apt-get update && apt-get upgrade -y
RUN apt-get install git glibc-source -y

# Install python packages for build_images script
RUN apt-get install python3 python3-pip -y
RUN pip3 install pyYaml gitPython pytz

# Install docker
RUN curl -fsSL get.docker.com | CHANNEL=stable sh
RUN apt-get install docker-ce docker-ce-cli containerd.io

WORKDIR /
COPY hack/build_images.py .

ENTRYPOINT ["python3", "-c"]