apiVersion: odf.ibm.com/v1alpha1
kind: FlashSystemCluster
metadata:
  name: flashsystemcluster-sample
  namespace: ibm-storage-odf
spec:
  # Add fields here
  name: flashsystem-xxx
  secret:
    name: fs-secrets-example
    namespace: ibm-storage-odf
  insecureSkipVerify: true
  defaultPool:
    storageclassName: odf-flashsystemcluster-sample
    poolName: Pool0
    fsType: ext4
    volumeNamePrefix: odf
    spaceEfficiency: thick

