#!/bin/bash

# Command line argument
ODF_NAMESPACE=$1
IBMCSI_NAMESPACE=$2
BASE_COLLECTION_PATH=$3
FILTER_STRING=$4

# Use must-gather as base path if no argument is passed
if [ "${BASE_COLLECTION_PATH}" = "" ]; then
    BASE_COLLECTION_PATH="must-gather"
fi
mkdir -p ${BASE_COLLECTION_PATH}

# Create dir for servicemonitor
LOG_PATH="${BASE_COLLECTION_PATH}/servicemonitor/"
mkdir -p ${LOG_PATH}

echo "INFO: Gathering ServiceMonitors"
ODF_SERVICEMONS=($(oc -n ${ODF_NAMESPACE} get servicemonitor --no-headers -o custom-columns=":metadata.name" -l odf="storage.ibm.com"))

if [ "${FILTER_STRING}" != "" ]; then

    for ODF_SERVICEMON in ${ODF_SERVICEMONS[@]}; do
        if echo ${ODF_SERVICEMON} | grep -Eq ${FILTER_STRING}; then
            echo "INFO: Gathering ServiceMonitor ${ODF_SERVICEMON}"
            oc -n ${ODF_NAMESPACE} get servicemonitor -o yaml ${ODF_SERVICEMON} > "${LOG_PATH}"/get_"${ODF_SERVICEMON}".yaml 2>&1
            oc -n ${ODF_NAMESPACE} describe servicemonitor ${ODF_SERVICEMON} > "${LOG_PATH}"/describe_"${ODF_SERVICEMON}".log 2>&1
        fi
    done

else

    for ODF_SERVICEMON in ${ODF_SERVICEMONS[@]}; do
        echo "INFO: Gathering ServiceMonitor ${ODF_SERVICEMON}"
        oc -n ${ODF_NAMESPACE} get servicemonitor -o yaml ${ODF_SERVICEMON} > "${LOG_PATH}"/get_"${ODF_SERVICEMON}".yaml 2>&1
        oc -n ${ODF_NAMESPACE} describe servicemonitor ${ODF_SERVICEMON} > "${LOG_PATH}"/describe_"${ODF_SERVICEMON}".log 2>&1
    done

fi
