#!/bin/bash
#
# Copyright contributors to the ibm-storage-odf-operator project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Command line argument
ODF_NAMESPACE=$1
IBMCSI_NAMESPACE=$2
BASE_COLLECTION_PATH=$3


# Use must-gather as base path if no argument is passed
if [ "${BASE_COLLECTION_PATH}" = "" ]; then
    BASE_COLLECTION_PATH="must-gather"
fi
mkdir -p ${BASE_COLLECTION_PATH}

# Create dir for crd
LOG_PATH="${BASE_COLLECTION_PATH}/crd/"
mkdir -p ${LOG_PATH}

echo "INFO: Gathering All CRDs installed by IBM"
oc get crd | grep ibm > "${LOG_PATH}"/All_CRDs_installed_by_IBM.log 2>&1

echo "INFO: Gathering CRD flashsystemclusters"
ODF_CRDS=($(oc -n ${ODF_NAMESPACE} get flashsystemclusters.odf.ibm.com --no-headers -o custom-columns=":metadata.name"))
for ODF_CRD in ${ODF_CRDS[@]}; do
    echo "INFO: Gathering CRD ${ODF_CRD}"
    oc -n ${ODF_NAMESPACE} get flashsystemclusters.odf.ibm.com -o yaml ${ODF_CRD} > "${LOG_PATH}"/get_"${ODF_CRD}".yaml 2>&1
    oc -n ${ODF_NAMESPACE} describe flashsystemclusters.odf.ibm.com ${ODF_CRD} > "${LOG_PATH}"/describe_"${ODF_CRD}".log 2>&1
done
