name: codespell

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: codespell
      uses: codespell-project/actions-codespell@v1
      with:
        check_filenames: true
        check_hidden: true
        skip: "./go.sum"
        ignore-words-list: NotIn
