name: codespell

on: workflow_dispatch

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: codespell
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        skip: "./go.sum"