name: commitlint

on: workflow_dispatch

jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: run commitlint
      uses: wagoid/commitlint-github-action@v3
      with:
        configFile: './.github/workflows/conf/commitlintrc.json'
        helpURL: |
          Some helpful links
          Naming Conventions -> https://commitlint.js.org/#/concepts-commit-conventions
          Rules -> https://commitlint.js.org/#/reference-rules
          How to Write a Good Git Commit Message -> https://chris.beams.io/posts/git-commit
