name: iso-ci.yaml

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [ published ]

env:
  VCS_URL: https://github.com/IBM/ibm-storage-odf-operator

jobs:
  precheck-and-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: check copyright
      run: |
        make check-copyright

    - name: run tests
      run: |
        make test

    - name: login to Quay.io
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_TOKEN }}

      # Setup for buildx
    - name: set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    # Debugging information
    - name: docker info
      run: docker info
    - name: buildx inspect
      run: docker buildx inspect

    - name: set output
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: get tag without v
      id: tag
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: battila7/get-version-action@v2

    # Build and (optionally) push the operator image
    - name: build the operator image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/ppc64le,linux/s390x
        build-args: |
          VCS_REF=${{ steps.tag.outputs.version-without-v || 'dev' }}-${{ steps.vars.outputs.sha_short }}
          VCS_URL=${{ env.VCS_URL }}
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'dev' tag, that won't be pushed, for non-release builds
        tags: quay.io/ibmodffs/ibm-storage-odf-operator:${{ steps.tag.outputs.version-without-v || 'dev' }}

    - name: generate bundle manifests and metadata
      run: |
        export IMAGE_TAG=${{ steps.tag.outputs.version-without-v || 'dev' }}
        make bundle
        rm -rf ./bundle/manifests/ibm-storage-odf-operator_v1_serviceaccount.yaml

    # Build and (optionally) push the operator bundle image
    - name: build the operator bundle image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./bundle.Dockerfile
        platforms: linux/amd64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        tags: quay.io/ibmodffs/ibm-storage-odf-operator-bundle:${{ steps.tag.outputs.version-without-v || 'dev' }}

      # Build and (optionally) push the operator must gather image
    - name: build the operator must gather image
      uses: docker/build-push-action@v2
      with:
        context: ./must-gather
        file: ./Dockerfile
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        tags: quay.io/ibmodffs/ibm-storage-odf-operator-must-gather:${{ steps.tag.outputs.version-without-v || 'dev' }}
